Add checked property on items in itemlist
Turplanlegger/turplanlegger-api pull request #188
Opened 2023-10-31 19:28 UTC by peseb

2023-10-31 20:20 UTC, sixcare requested changes
Missing quite a lot :(

2023-10-31 20:20 UTC, sixcare commented on turplanlegger/models/list_items.py
Missing from docstring: https://github.com/Turplanlegger/turplanlegger-api/blob/07492feff3637768d072f2e276f7acdad8084273/turplanlegger/models/list_items.py#L12

Missing from __repr__: https://github.com/Turplanlegger/turplanlegger-api/blob/07492feff3637768d072f2e276f7acdad8084273/turplanlegger/models/list_items.py#L51

Missing from mini_serialize: https://github.com/Turplanlegger/turplanlegger-api/blob/07492feff3637768d072f2e276f7acdad8084273/turplanlegger/models/list_items.py#L113

2023-11-21 17:11 UTC, peseb commented on turplanlegger/models/list_items.py
Added to mini_serialize, was already in docstring & repr

2023-11-21 17:48 UTC, sixcare approved these changes
GJ 😁

2024-01-07 16:05 UTC, merged